import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

interface ReportOptions {
  title: string;
  subtitle?: string;
  columns: string[];
  data: any[][];
  summaryCards?: { label: string; value: string }[];
  chartElementId?: string;
}

export async function generateFinancialPDF(options: ReportOptions): Promise<Blob> {
  const doc = new jsPDF("p", "pt", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(139, 92, 246); // Brand Purple
  doc.rect(0, 0, pageWidth, 80, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("TechNext Technologies", 40, 45);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Business Operations ERP", pageWidth - 40, 45, { align: "right" });

  // Report Title
  doc.setTextColor(30, 41, 59); // Slate 800
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(options.title, 40, 120);

  let currentY = 140;

  if (options.subtitle) {
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(options.subtitle, 40, currentY);
    currentY += 30;
  }

  // Meta Info
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 40, currentY);
  doc.text(`Generated By: Automated System`, pageWidth - 40, currentY, { align: "right" });
  currentY += 30;

  // Summary Cards
  if (options.summaryCards && options.summaryCards.length > 0) {
    const cardWidth = (pageWidth - 80 - (10 * (options.summaryCards.length - 1))) / options.summaryCards.length;
    let startX = 40;
    
    options.summaryCards.forEach(card => {
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(startX, currentY, cardWidth, 60, 4, 4, "FD");
      
      doc.setTextColor(100, 116, 139);
      doc.setFontSize(10);
      doc.text(card.label, startX + 10, currentY + 20);
      
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text(card.value, startX + 10, currentY + 45);
      
      doc.setFont("helvetica", "normal");
      startX += cardWidth + 10;
    });
    currentY += 80;
  }

  // Chart (If element ID provided)
  if (options.chartElementId) {
    const chartEl = document.getElementById(options.chartElementId);
    if (chartEl) {
      try {
        const canvas = await html2canvas(chartEl, { scale: 2 });
        const imgData = canvas.toDataURL("image/png");
        const imgProps = doc.getImageProperties(imgData);
        const pdfWidth = pageWidth - 80;
        const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
        
        doc.addImage(imgData, "PNG", 40, currentY, pdfWidth, pdfHeight);
        currentY += pdfHeight + 30;
      } catch (err) {
        console.error("Failed to capture chart:", err);
      }
    }
  }

  // Data Table
  autoTable(doc, {
    startY: currentY,
    head: [options.columns],
    body: options.data,
    theme: "striped",
    headStyles: { fillColor: [139, 92, 246] },
    margin: { top: 40, right: 40, bottom: 40, left: 40 },
    didDrawPage: (data: any) => {
      // Footer
      const str = `Page ${doc.internal.pages.length - 1}`;
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.getHeight() - 20);
      doc.text("TechNext CRM © " + new Date().getFullYear(), pageWidth - 40, doc.internal.pageSize.getHeight() - 20, { align: "right" });
    }
  });

  return doc.output("blob");
}

export function downloadBlobAsFile(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
